set nocompatible

filetype plugin indent on
syntax on

set number
set cursorline
set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20
set nowrap
set showcmd
set ruler
set laststatus=2
set wildmenu
set wildmode=longest:full,full
set completeopt=menuone,noinsert,noselect
set clipboard=unnamedplus
set signcolumn=yes
set updatetime=100

let mapleader = " "
let maplocalleader = ","

nnoremap <Space> <Nop>
nnoremap , <Nop>

call plug#begin()

Plug 'sheerun/vim-polyglot'
Plug 'easymotion/vim-easymotion'
Plug 'liuchengxu/vim-which-key'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'prabirshrestha/vim-lsp'

call plug#end()

set noshowmode

let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1

highlight SignColumn ctermbg=NONE guibg=NONE
highlight GitGutterAdd    guifg=#009900 ctermfg=2
highlight GitGutterChange guifg=#bbbb00 ctermfg=3
highlight GitGutterDelete guifg=#ff2222 ctermfg=1

let g:gitgutter_enabled = 1
let g:gitgutter_sign_column_always = 1
let g:gitgutter_sign_added = '+L'
let g:gitgutter_sign_modified = '~L'
let g:gitgutter_sign_removed = '__'
let g:gitgutter_sign_removed_first_line = '__'
let g:gitgutter_sign_modified_removed = '~L'

" Jump between hunks
nmap [c <Plug>(GitGutterPrevHunk)
nmap ]c <Plug>(GitGutterNextHunk)

" Hunk actions
nmap <Leader>hs <Plug>(GitGutterStageHunk)
nmap <Leader>hu <Plug>(GitGutterUndoHunk)
nmap <Leader>hp <Plug>(GitGutterPreviewHunk)

let g:gitgutter_max_signs = 1000

nnoremap <silent> , :WhichKey '<Space>'<CR>

nnoremap <leader>j <Plug>(easymotion-overwin-f)
nnoremap <leader>k <Plug>(easymotion-overwin-f2)

" Python

if executable('ruff')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'ruff',
        \ 'cmd': {server_info->['ruff', 'server']},
        \ 'allowlist': ['python'],
        \ 'workspace_config': {},
        \ })
endif

augroup python_ruff
  autocmd!
  autocmd BufWritePre *.py if executable('ruff') | silent execute '%!ruff format -' | endif
augroup END

augroup ipynb_json
  autocmd!
  autocmd BufRead,BufNewFile *.ipynb setfiletype json
augroup END
